# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92f7e791b80d8af32236c368c02fd0eff76c3d92120d2e4e6c82e87b9cb2b9df020f956a813a121b7f665c5462b12f1b54b5f4b30b492d75bb623f135842abba

test:
  secret_key_base: 45bc0d32b6ef624964fb6b9020fa2a676804e404dc36f683807b1755e0b07e453cee7ac122fe5fd16c0a0ea68a321339509303e591e0f202a4e19e1fc60588b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
