# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f89a811359b712ceb7f41d2573c388578b16cc5a3e231fe48db3aa916c4c09affaca53fac2b378f92708274544bf2ef918f59070d10e835fc885a5214b3a818

test:
  secret_key_base: b7fac142c501907da1cf5d58a2ca4a8a3f0c772a631df689622407561ecd47f30e5a188149fc27bc39fd1dc339ed680ef1ee30f8e10dbc9a142f7fc7b087f851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
