# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d700c0b70b6b01cee0e24973b4e3a0b87dfa245814921633db79eb30b528885bc6f17c397441649dc4e5457d97b1d100aca613fe4f71aa52a94bc6feb75e335

test:
  secret_key_base: 80da9c565c8238f2ec05d8921048c550c2636d3c9233ae8fc5a231b6498349a29f60d4e09ca72c96b8eb690258b61cd9f9bbac1586cb29b566ebaba507b469a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
