# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a116cb16defe90db6a111c181b976f8c26031e38eb76d6aaebcee4f46605d8932ba3409b7b915db913cdf5ec7f79cf57289194629a9e69f1f5d4fffe58e42d2

test:
  secret_key_base: de7a848269f3359294109ec9fc98261acd346076201d8852a8431d586738ee294dd47ab188aca9317e490743a21f9426b3df4634935d34162abe21543785d248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
